  name: slobodniodnikotina
  description: "Aplikacija za praćenje napretka nakon prestanka pušenja. Pomagač za korisnike programa Slobodni od Nikotina "
  publish_to: 'none'

  version: 2.0.0+1

  environment:
    sdk: ">=3.8.1 <4.0.0"

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.8
    intl: ^0.18.1
    shared_preferences: ^2.2.2

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^5.0.0
    flutter_launcher_icons: ^0.14.4
  flutter_icons:
    image_path: "slike/icon.png"
    ios: true
    android: true
    

  flutter:
    uses-material-design: true
    assets:
      # pocetna slika
      - slike/pticica.png
      
      # achievementi slike
      - slike/colorheart.png
      - slike/colorlungs.png
      - slike/colormountain.png
      - slike/color7days.png
      - slike/colorptica.png
      - slike/color30days.png
      - slike/mdi_heart.png
      - slike/mdi_lungs.png
      - slike/mountain-gray.png
      - slike/calendar7daysgray.png
      - slike/ptica-gray.png
      - slike/calendar30daysgray.png

